<?php $review = $this->getStoreReview(); ?>
<div class="dashboard">
    <div class="page-title">
        <h1><?php echo $this->__('My Store Review') ?></h1>
    </div>
    <?php if ($this->getStoreReview()->getCustomerId() !== null): ?>
        <div class="">
            <div class="box-head">
                <h2 class="legend"><?php echo $this->escapeHtml($review->getTitle()); ?></h2>
            </div>
            <br>
            <div><?php echo $this->escapeHtml($review->getReview()); ?></div>
            <br>
            <div class="buttons-set">
                <!--            <p class="back-link"><a href="-->
                <?php //echo $this->getBackUrl() ?><!--"><small>&laquo; </small>-->
                <?php //echo $this->__('Back to My Reviews') ?><!--</a></p>-->
                <p class="edit-link"><a href="<?php echo $this->getEditUrl() ?>"><?php echo $this->__('Edit review') ?></a></p>
                <p class="delete-link"><a href="<?php echo $this->getDeleteUrl() ?>"><?php echo $this->__('Delete review') ?></a></p>
            </div>
        </div>
    <?php else: ?>
        <div>You haven't submitted a store review yet, <a href="/storereview/index/edit">submit one now.</a></div>
    <?php endif; ?>
</div>
